# Generated by Django 3.1.7 on 2021-05-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usermsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('messg', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='userAcc',
        ),
    ]
