# Generated by Django 3.1.7 on 2021-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0002_auto_20210529_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermsg',
            name='display',
            field=models.TextField(blank=True),
        ),
    ]
